alter session set "_ORACLE_SCRIPT"=true
CREATE USER VS
  IDENTIFIED BY VS
  DEFAULT TABLESPACE users
  TEMPORARY TABLESPACE temp
  PROFILE DEFAULT;
 
GRANT CONNECT TO VS;
GRANT CREATE SESSION TO VS;
GRANT RESOURCE TO VS;
GRANT UNLIMITED TABLESPACE TO VS;
GRANT CREATE VIEW TO VS;